rails/ostinato/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: 'u'
  resources :users
  resources :topics, except: :show do
    resources :posts
  end
  resources :file_resources, only: %i[index new create destroy]
  get "/file_resources/download" => "file_resources#download_file"
  get "/pages/:page" => "pages#show"
  root "pages#home"
end

rails/ostinato/app/models/topic.rb
class Topic < ApplicationRecord
  has_many :posts

  validates :codename, presence: true

  def last_post
    if posts.count.positive?
      posts.order('updated_at DESC').first
    end
  end
end

rails/ostinato/app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_admin!, only: %i[new edit create update destroy]
  before_action :set_topic, only: %i[edit update destroy]
  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit; end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to topics_url, notice: I18n.t('topics.topic_created') }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to topics_url, notice: I18n.t('topics.topic_updated') }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url, notice: I18n.t('topics.topic_deleted') }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_topic
    @topic = Topic.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def topic_params
    params.require(:topic).permit(:codename, :public)
  end
end

rails/ostinato/app/helpers/topics_helper.rb
module TopicsHelper
end

rails/ostinato/app/views/topics/_form.html.erb
<%= form_for(topic) do |f| %>
  <% if topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% topic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :codename %><br />
    <%= f.text_field :codename, class: "form-control", style: "max-width: 500px"%>
  </div>
  <div class="checkbox">
    <%= f.label :public, id: "public-checkbox" do %>
      <%= f.check_box :public, class: "form-control" %>
      <span class="cr"><i class="cr-icon fa fa-check"></i></span>
      <%= Topic.human_attribute_name("public") %>
    <% end %>
  </div>
  <br/>
  <div class="actions">
    <%= f.submit I18n.t('topics.create_topic'), class: 'btn btn-success'%>
  </div>
<% end %>

rails/ostinato/app/views/topics/edit.html.erb
<div class="form-container">
    <%= link_to I18n.t('show'), topic_posts_path(@topic), class: 'btn btn-info' %>
    <%= link_to I18n.t('back'), topics_path, class: 'btn btn-warning' %>
    <br/><br/>
    <h1><%= I18n.t('topics.edit_topic') %> </h1>
    <br/>
    <%= render 'form', topic: @topic %>
    <br/>
</div>

rails/ostinato/app/views/topics/index.html.erb
<% if admin_signed_in? %>
  <div class="row">
    <div class="col-md-1"> </div>
      <div class="col-md-10">
        <%= link_to I18n.t('topics.new_topic'), new_topic_path, class: 'btn btn-success' %>
      </div>
    <div class="col-md-1"> </div>
  </div>
<% end %>

</br>

<% @topics.each do |topic| %>
  <div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-10 singletopic">
      <div class="col-md-10">
        <% if admin_signed_in? %>
        <%= link_to 'Edit', edit_topic_path(topic), class: 'btn btn-warning btn-xs' %>
        <%= link_to 'Delete', topic, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs' %>
        <% end %>
        <h3> <% if topic.public %>
                <% p = "[P]" else p = "" %>
              <% end %>
              <%= link_to topic.codename + p,  topic_posts_path(topic) %> 
        </h3>
      </div>
      <% if topic.posts.any? %>
        <div class="col-md-9">
            <h4> Ostatnia aktywność: <i> <%= topic.last_post.title %> </i></h4>
        </div>
        <div class="col-md-3">
          <h4> <%= topic.last_post.updated_at.strftime("%d.%m.%Y %H:%M")%> </h4>
        </div>
      <% else %>
        <div class="col-md-3">
            <h4> <%= I18n.t('topics.no_posts') %> </h4>
        </div>
      <% end %>
    </div>
    <div class="col-md-1"></div>
    <div class="col-md-12">
      <hr/>
    </div>
  </div>
<% end %>

<br>

rails/ostinato/app/views/topics/new.html.erb
<div class="form-container">
    <%= link_to I18n.t('back'), topics_path, class: 'btn btn-warning' %>
    <br/><br/>
    <h1><%= I18n.t('topics.new_topic') %> </h1>
    <br/>
    <%= render 'form', topic: @topic %>
</div>