rails/ostinato/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: 'u'
  resources :users
  resources :topics, except: :show do
    resources :posts
  end
  resources :file_resources, only: %i[index new create destroy]
  get "/file_resources/download" => "file_resources#download_file"
  get "/pages/:page" => "pages#show"
  root "pages#home"
end

rails/ostinato/app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :topic
  has_many :likes, as: :likeable
  has_many :comments

  validates :content, presence: true
end

rails/ostinato/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_filter :load_parent
  before_action :set_post, only: %i[show edit update destroy]
  before_action :authenticate_author!, only: %i[edit update destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = @topic.posts.order('updated_at DESC')
  end

  # GET /posts/1
  # GET /posts/1.json
  def show; end

  # GET /posts/new
  def new
    @post = @topic.posts.new
  end

  # GET /posts/1/edit
  def edit; end

  # POST /posts
  # POST /posts.json
  def create
    @post = @topic.posts.new(post_params)
    @post.user_id = current_user.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to [@topic, @post], notice: I18n.t('posts.post_created') }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to [@topic, @post], notice: I18n.t('posts.post_updated') }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html do
        redirect_to topic_posts_path(@topic),
        notice: I18n.t('posts.post_deleted')
      end
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = @topic.posts.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
    params.require(:post).permit(:title, :content)
  end

  def load_parent
    @topic = Topic.find(params[:topic_id])
  end

  def authenticate_author!
    authenticate_user!
    unless current_user.id == @post.user.id || current_user.is_admin?
      flash[:alert] = I18n.t('posts.only_author')
      redirect_to root_path
    end
  end
end

rails/ostinato/app/helpers/posts_helper.rb
module PostsHelper
end

rails/ostinato/app/views/posts/_form.html.erb
<%= form_for([@topic, @post]) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br />
    <%= f.text_field :title, class: "form-control"%>
  </div>
  <div class="form-group">
    <%= f.label :content %><br />
    <%= f.cktext_area :content, class: "form-control", rows: 5 %>
  </div>
  <br />
  <%= f.submit I18n.t('posts.create_post'), class: 'btn btn-success' %>
<% end %>

rails/ostinato/app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', topic_post_path(@topic, @post) %> |
<%= link_to 'Back', topic_posts_path(@topic) %>

rails/ostinato/app/views/posts/index.html.erb
<div class="col-xs-1"> </div>
<div class="col-xs-11">
  <%= link_to I18n.t('posts.new_post'), new_topic_post_path, class: 'btn btn-success' %>
</div>

<center> <h1> <%=@topic.codename %></h1> </center>

<% if @posts.count == 0 %>
  <hr class="black-separator">
  <center> <h2> Brak postów do wyświetlenia </h2> </center>
<% end %>

<% @posts.each do |post| %>
      <div class="news">
            <div class="row">
                <div class="col-xs-10 content">
                    <div class="row">
                      <div class="col-xs-9">
                        <h5 class="date"><span class="glyphicon glyphicon-calendar"></span> <%= post.created_at.strftime("%d.%m.%Y %H:%M") %></h5>
                      </div>
                      <div class="col-xs-3 right-align">
                        <% if author?(post)%>
                          <%= link_to I18n.t('edit'), edit_topic_post_path(@topic, post), class: 'btn btn-warning btn-xs' %>
                          <%= link_to I18n.t('delete'), [@topic, post], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs' %>
                        <% end %>  
                      </div>
                    </div>
                    <h2 class='no-margin'> <%= link_to post.title, topic_post_path(@topic, post) %> </h2>
                    <p> <%= I18n.t('topics.author') %>:
                        <%= post.user.name %>
                        <%= post.user.surname %>
                    </p>
                </div>
            </div>
        </div>
<% end %>

rails/ostinato/app/views/posts/new.html.erb
<div class="form-container">
<%= link_to I18n.t('back'), topic_posts_path(@topic), class: 'btn btn-warning' %>

<h1><%= I18n.t('posts.new_post') %> </h1>

<%= render 'form', post: @post %>
</div>

rails/ostinato/app/views/posts/show.html.erb
<div class="row">
  <div class="col-xs-1"> </div>
  <div class="col-xs-10"> <%= link_to I18n.t('back'), topic_posts_path(@topic), class: 'btn btn-warning' %> </div>
</div>

<br />

<div class="news">
  <div class="row">
    <div class="col-xs-10 content">
      <div class="row">
        <div class="col-xs-2">
          <h5 class="date"><span class="glyphicon glyphicon-calendar"></span> <%= @post.created_at.strftime("%d.%m.%Y %H:%M") %></h5>
        </div>
        <div class="col-xs-7">
          <h5><span class="glyphicon glyphicon-user"></span>
          <%= I18n.t('topics.author') %>:
          <%= @post.user.name %>
          <%= @post.user.surname %>
          </h5>
        </div>
        <div class="col-xs-3 right-align">
          <% if author?(@post)%>
            <%= link_to I18n.t('edit'), edit_topic_post_path(@topic, @post), class: 'btn btn-warning btn-xs' %>
            <%= link_to I18n.t('delete'), [@topic, @post], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs' %>
          <% end %>        
        </div>
      </div>
      <h2> <%= link_to @post.title, topic_post_path(@topic, @post)  %> </h2>
      <hr class="black-separator">
      <p> <%= simple_format @post.content %> </p>
    </div>
  </div>
</div>