rails/ostinato/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: 'u'
  resources :users
  resources :topics, except: :show do
    resources :posts
  end
  resources :file_resources, only: %i[index new create destroy]
  get "/file_resources/download" => "file_resources#download_file"
  get "/pages/:page" => "pages#show"
  root "pages#home"
end

rails/ostinato/app/views/layouts/_footer.html.erb
<footer>
  Ostinato - <%= I18n.t('title') %> <sup> &copy; </sup>; <%= I18n.t('rights') %>
</footer>

rails/ostinato/app/views/layouts/_header.html.erb
<header>
    <div class="row" id="main-nav">
        <div class="col-md-4 vertical-align paddingRemove">
            <%= link_to (image_tag("logo.png", id: "logo")), {:controller => "/pages", :action => "home"} %>
            <div class="col-md-8 vertical-align" align="left">
                <div class="col-md-6 vertical-align" align="left">
                    <%= link_to :controller => "/pages", :action => "home" do %>
                        <h1><span class="label label-danger">Ostinato</span></h1>
                    <% end %>
                </div>
                <div class="col-md-6 vertical-align" align="left"></div>
            </div>
        </div>
        <div class="col-md-4" align="center">
            <div class="language" align="center">
                <%= image_tag("flag.png", id: "flag") %>
                <%= link_to_unless I18n.locale == :pl, "PL", locale: :pl %>
                <%= link_to_unless I18n.locale == :en, "EN", locale: :en %>
            </div>
        </div>
        <div class="col-md-4 logReg">
            <div class="col-md-5">
                <% unless user_signed_in? %>
                    <%= link_to I18n.t('registration'), new_user_registration_url %>
                <% end %>
            </div>
            <div class="col-md-5">
                <% if user_signed_in? %>
                    <%= link_to I18n.t('sign_out'), destroy_user_session_path, :method => :delete  %>
                <% else %>
                    <%= link_to I18n.t('login'), new_user_session_url %>
                <% end %>
            </div>
        </div>
    </div>
    <%= render 'layouts/navbar' %>           
</header>

rails/ostinato/app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>

rails/ostinato/app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#menu" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>

        <div class="collapse navbar-collapse" id="menu">
            <ul class="nav navbar-nav">
                <li><%= link_to I18n.t('news'), {:controller => "/pages", :action => "home"}%> </li>
                <li><%= link_to I18n.t('about'), {:controller => "/pages", :action => "show", :page => "about"}%> </li>
                <li><%= link_to I18n.t('contact'), {:controller => "/pages", :action => "show", :page => "contact"}%> </li>
                <% if admin_signed_in? %>
                <li><%= link_to I18n.t('admin_users'), users_path %> </li>
                <% end %>
                <% if user_signed_in? %>
                <li><%= link_to I18n.t('topics_tab'), topics_path %> </li>  
                <% end %>
                <% if user_signed_in? %>
                <li><%= link_to I18n.t('files_tab'), file_resources_path %> </li>  
                <% end %>
            </ul>
        </div>
    </div>
</nav>

rails/ostinato/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pl">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Ostinato</title>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
    <div id="wrapper">
        <%= render "layouts/header" %>
        <main>
            <%= render "layouts/messages" %>
            <%= yield %>
        </main>
        <%= render "layouts/footer" unless action_name === "index" %>
    </div>
</body>
</html>